import '../models/service_product.dart';

// Master data for all services and their subcategories
final Map<String, Map<String, List<ServiceProduct>>> serviceProducts = {
// 👕 LAUNDRY
  'Laundry': {
    /// WASHING
    'Washing': [
      ServiceProduct(
        name: 'Shirt Washing',
        price: 60,
        imagePath: 'assets/wash.jfif',
        description:
            'Professional cleaning to remove dirt, sweat, and stains while keeping fabric fresh and soft.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Fresh and clean shirt washing service.',
        includes: [
          'Deep fabric cleaning',
          'Quality detergent washing',
          'Fabric softener treatment',
          'Fresh fragrance finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Pant Washing',
        price: 70,
        imagePath: 'assets/pant.jpg',
        description:
            'Proper cleaning for trousers and everyday pants while maintaining fabric quality and color.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Proper washing for everyday pants.',
        includes: [
          'Deep fabric cleaning',
          'Color protection',
          'Fabric softener treatment',
          'Proper drying process',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Suit Washing',
        price: 200,
        imagePath: 'assets/blazzer.jpg',
        description:
            'Careful washing for formal suits with premium fabric care.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Careful washing for formal suits.',
        includes: [
          'Premium fabric care',
          'Deep stain removal',
          'Shape retention',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Saree Washing',
        price: 150,
        imagePath: 'assets/saree.jpg',
        description:
            'Gentle cleaning for delicate sarees while protecting fabric, color, and design.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Gentle washing for delicate sarees.',
        includes: [
          'Gentle washing process',
          'Fabric protection',
          'Color-safe cleaning',
          'Fresh fragrance finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Curtain Washing',
        price: 120,
        imagePath: 'assets/curtain.jpg',
        description:
            'Removes dust, stains, and allergens to keep curtains fresh and hygienic.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Dust-free and fresh curtain washing.',
        includes: [
          'Deep dust removal',
          'Fabric-safe washing',
          'Color protection',
          'Fresh fragrance',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Shoe Washing',
        price: 130,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning to remove dirt, stains, and odor while restoring freshness.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Clean and refreshed shoes.',
        includes: [
          'Dirt and stain removal',
          'Deep washing process',
          'Odor cleaning',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bedsheet Washing',
        price: 90,
        imagePath: 'assets/sheets.jpg',
        description:
            'Ensures hygienic cleaning and removal of dirt, bacteria, and stains.',
        time: '24 Hours',
        discount: 8,
        slogan: 'Soft, fresh and hygienic bedsheets.',
        includes: [
          'Hygienic deep cleaning',
          'Soft fabric care',
          'Fresh fragrance finish',
          'Proper drying and folding',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 DRY CLEANING
    'Dry Cleaning': [
      ServiceProduct(
        name: 'Shirt Dry Cleaning',
        price: 120,
        imagePath: 'assets/shirt.jpg',
        description: 'Professional dry cleaning for shirts with stain removal.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Professional dry cleaning for shirts.',
        includes: [
          'Deep stain removal',
          'Premium fabric care',
          'Safe chemical cleaning',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Suit Dry Cleaning',
        price: 350,
        imagePath: 'assets/blazzer.jpg',
        description: 'Premium cleaning service for formal suits.',
        time: '72 Hours',
        discount: 15,
        slogan: 'Premium cleaning for formal suits.',
        includes: [
          'Luxury fabric care',
          'Deep stain removal',
          'Shape retention',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Saree Dry Cleaning',
        price: 250,
        imagePath: 'assets/saree.jpg',
        description: 'Safe cleaning for delicate sarees with color protection.',
        time: '72 Hours',
        discount: 12,
        slogan: 'Safe dry cleaning for delicate sarees.',
        includes: [
          'Color protection',
          'Fabric-safe cleaning',
          'Soft finishing',
          'Premium care',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Blazer Dry Cleaning',
        price: 300,
        imagePath: 'assets/blazzer.jpg',
        description: 'Expert cleaning for blazers and jackets.',
        time: '72 Hours',
        discount: 10,
        slogan: 'Keep your blazer sharp and fresh.',
        includes: [
          'Odor removal',
          'Shape retention',
          'Soft fabric care',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 IRONING
    'Ironing': [
      ServiceProduct(
        name: 'Shirt Ironing',
        price: 15,
        imagePath: 'assets/ironing.jpg',
        description: 'Crisp and wrinkle-free shirt ironing.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Crisp and wrinkle-free shirts.',
        includes: [
          'Smooth finish',
          'Fabric-safe heat',
          'Neat folding',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Pant Ironing',
        price: 20,
        imagePath: 'assets/pant.jpg',
        description: 'Perfectly pressed pants.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Perfectly pressed pants.',
        includes: [
          'Sharp crease',
          'Wrinkle-free',
          'Professional finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Dress Ironing',
        price: 30,
        imagePath: 'assets/dress.jpg',
        description: 'Wrinkle-free dresses.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Wrinkle-free dresses every time.',
        includes: [
          'Soft pressing',
          'Neat finish',
          'Quick service',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Kids Clothes Ironing',
        price: 10,
        imagePath: 'assets/kids.jfif',
        description: 'Gentle ironing for kids’ clothes.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Soft care for little ones.',
        includes: [
          'Delicate handling',
          'Smooth finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 CURTAIN CLEANING
    'Curtain Cleaning': [
      ServiceProduct(
        name: 'Window Curtain Cleaning',
        price: 120,
        imagePath: 'assets/curtain.jpg',
        description: 'Dust-free curtain cleaning.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Dust-free and fresh curtains.',
        includes: [
          'Deep dust removal',
          'Fabric-safe wash',
          'Fresh fragrance',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Heavy Curtain Cleaning',
        price: 200,
        imagePath: 'assets/curtain.jpg',
        description: 'Deep cleaning for heavy curtains.',
        time: '72 Hours',
        discount: 12,
        slogan: 'Deep cleaning for heavy curtains.',
        includes: [
          'Heavy fabric care',
          'Stain removal',
          'Odor removal',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Luxury Curtain Cleaning',
        price: 300,
        imagePath: 'assets/curtain.jpg',
        description: 'Premium cleaning for luxury curtains.',
        time: '72 Hours',
        discount: 15,
        slogan: 'Luxury care for your curtains.',
        includes: [
          'Color protection',
          'Premium fabric care',
          'Fresh scent',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 SHOE CLEANING
    'Shoe Cleaning': [
      ServiceProduct(
        name: 'Sports Shoe Cleaning',
        price: 150,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning for sports shoes with stain and odor removal.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Restore the freshness of sports shoes.',
        includes: [
          'Dirt and stain removal',
          'Odor cleaning',
          'Deep washing process',
          'Proper drying'
        ],
        process: [
          'Step 1: Inspection',
          'Step 2: Cleaning',
          'Step 3: Drying',
          'Step 4: Final check'
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Leather Shoe Cleaning',
        price: 200,
        imagePath: 'assets/leather.jpg',
        description:
            'Premium cleaning service for leather shoes with special care.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Premium care for leather shoes.',
        includes: [
          'Dirt removal',
          'Leather-safe cleaning',
          'Odor treatment',
          'Proper drying'
        ],
        rating: 4.3,
        process: [
          'Step 1: Inspection',
          'Step 2: Leather-safe cleaning',
          'Step 3: Conditioning',
          'Step 4: Drying'
        ],
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Sneaker Cleaning',
        price: 180,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning for sneakers to maintain style and hygiene.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Deep cleaning for trendy sneakers.',
        includes: ['Stain removal', 'Odor cleaning', 'Deep wash', 'Drying'],
        process: [
          'Step 1: Inspection',
          'Step 2: Cleaning',
          'Step 3: Drying',
          'Step 4: Finishing'
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Boot Cleaning',
        price: 220,
        imagePath: 'assets/boots.jfif',
        description: 'Special cleaning for boots to maintain shine and shape.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Shiny and fresh boots every time.',
        includes: [
          'Deep dirt removal',
          'Polish treatment',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 BEDSHEET CLEANING
    'Bedsheet Cleaning': [
      ServiceProduct(
        name: 'Single Bedsheet Cleaning',
        price: 80,
        imagePath: 'assets/sheets.jpg',
        description: 'Hygienic bedsheet cleaning.',
        time: '24 Hours',
        discount: 8,
        slogan: 'Fresh and hygienic bedsheets.',
        includes: [
          'Hygienic wash',
          'Soft fabric care',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Double Bedsheet Cleaning',
        price: 120,
        imagePath: 'assets/sheets.jpg',
        description: 'Soft and clean bedsheets.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Soft and clean double bedsheets.',
        includes: [
          'Deep cleaning',
          'Soft finish',
          'Fresh fragrance',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bedsheet Deep Cleaning',
        price: 180,
        imagePath: 'assets/sheets.jpg',
        description: 'Deep hygienic cleaning.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Deep hygienic cleaning for bedsheets.',
        includes: [
          'Bacteria removal',
          'Deep stain cleaning',
          'Premium wash',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Luxury Bedsheet Cleaning',
        price: 250,
        imagePath: 'assets/sheets.jpg',
        description: 'Premium care for luxury bedsheets.',
        time: '48 Hours',
        discount: 15,
        slogan: 'Luxury care for your bedsheets.',
        includes: [
          'Fabric-safe deep wash',
          'Premium finishing',
          'Fresh fragrance',
        ],
        rating: 5,
        id: '',
        service: '',
      ),
    ],
  },
  
// 🚰 PLUMBING
  'Plumbing': {
    /// 🔹 PIPE REPAIR
    'Pipe Repair': [
      ServiceProduct(
        name: 'Pipe Leakage Repair',
        price: 400,
        imagePath: 'assets/pipe_repair.jpg',
        description: 'Fix leaking pipes and restore smooth water flow.',
        time: '30-60 mins',
        discount: 15,
        slogan: 'Quick fix for leaking pipes.',
        includes: [
          'Pipe inspection',
          'Leak detection',
          'Repair work',
          'Testing',
        ],
        process: [
          'Inspection',
          'Problem identification',
          'Repair',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Broken Pipe Fix',
        price: 600,
        imagePath: 'assets/tap_install.jpg',
        description: 'Repair damaged pipes efficiently.',
        time: '45-90 mins',
        discount: 20,
        slogan: 'Reliable pipe repair solution.',
        includes: [
          'Damage inspection',
          'Pipe fixing',
          'Seal testing',
        ],
        process: [
          'Inspect damage',
          'Repair pipe',
          'Test flow',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Pipe Replacement',
        price: 1200,
        imagePath: 'assets/tap_install.jpg',
        description: 'Complete pipe replacement service.',
        time: '60-90 mins',
        discount: 20,
        slogan: 'Long-lasting pipe replacement.',
        includes: [
          'Old pipe removal',
          'New pipe installation',
          'Testing',
        ],
        rating: 4.3,
        process: [
          'Remove old pipe',
          'Install new pipe',
          'Testing',
        ],
        id: '',
        service: '',
      ),
    ],

    /// 🔹 LEAKAGE FIX
    'Leakage Fix': [
      ServiceProduct(
        name: 'Kitchen Pipe Leakage Fix',
        price: 400,
        imagePath: 'assets/kitchen.jpg',
        description: 'Stop kitchen leakage instantly.',
        time: '40-60 mins',
        discount: 10,
        slogan: 'Quick kitchen leak solution.',
        includes: [
          'Leak detection',
          'Seal fixing',
          'Testing',
        ],
        rating: 4.5,
        process: [
          'Detect leak',
          'Fix leakage',
          'Testing',
        ],
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bathroom Leakage Fix',
        price: 450,
        imagePath: 'assets/bathroom.jpg',
        description: 'Fix bathroom pipe leakages.',
        time: '40-60 mins',
        discount: 12,
        slogan: 'Bathroom leak repair experts.',
        includes: [
          'Inspection',
          'Leak fixing',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 TAP INSTALLATION
    'Tap Installation': [
      ServiceProduct(
        name: 'New Tap Installation',
        price: 300,
        imagePath: 'assets/tap_install.jpg',
        description: 'Install new taps professionally.',
        time: '20-40 mins',
        discount: 10,
        slogan: 'Smooth tap installation.',
        includes: [
          'Tap fitting',
          'Connection setup',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Tap Replacement',
        price: 350,
        imagePath: 'assets/pipe_repair.jpg',
        description: 'Replace old taps easily.',
        time: '20-40 mins',
        discount: 12,
        slogan: 'Upgrade your tap easily.',
        includes: [
          'Remove old tap',
          'Install new tap',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 DRAIN CLEANING
    'Drain Cleaning': [
      ServiceProduct(
        name: 'Kitchen Drain Cleaning',
        price: 400,
        imagePath: 'assets/cleaning.png',
        description: 'Remove kitchen blockages.',
        time: '45-60 mins',
        discount: 10,
        slogan: 'Clog-free kitchen drains.',
        includes: [
          'Drain cleaning',
          'Block removal',
          'Pipe flushing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Blocked Drain Fix',
        price: 600,
        imagePath: 'assets/drain.jpg',
        description: 'Clear heavy blockages.',
        time: '60 mins',
        discount: 15,
        slogan: 'Heavy blockage solution.',
        includes: [
          'Inspection',
          'Cleaning',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 BATHROOM REPAIR
    'Bathroom Repair': [
      ServiceProduct(
        name: 'Shower Repair',
        price: 400,
        imagePath: 'assets/bathroom.jpg',
        description: 'Fix shower issues quickly.',
        time: '40-60 mins',
        discount: 10,
        slogan: 'Quick shower repair.',
        includes: [
          'Inspection',
          'Repair',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bathroom Pipe Repair',
        price: 600,
        imagePath: 'assets/tap.jpg',
        description: 'Repair bathroom pipes.',
        time: '45-60 mins',
        discount: 15,
        slogan: 'Reliable bathroom repair.',
        includes: [
          'Pipe repair',
          'Leak fix',
          'Testing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 TOILET REPAIR
    'Toilet Repair': [
      ServiceProduct(
        name: 'Toilet Flush Repair',
        price: 300,
        imagePath: 'assets/tap.jpg',
        description: 'Fix flush problems.',
        time: '30-45 mins',
        discount: 10,
        slogan: 'Quick flush repair.',
        includes: [
          'Flush repair',
          'Testing',
        ],
        rating: 4.4,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Toilet Leakage Fix',
        price: 450,
        imagePath: 'assets/tap.jpg',
        description: 'Stop toilet leakage.',
        time: '30-45 mins',
        discount: 10,
        slogan: 'Leak-free toilet solution.',
        includes: [
          'Leak fixing',
          'Seal check',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 SINK INSTALLATION
    'Sink Installation': [
      ServiceProduct(
        name: 'Kitchen Sink Installation',
        price: 800,
        imagePath: 'assets/kitchen.jpg',
        description: 'Install kitchen sinks perfectly.',
        time: '40-60 mins',
        discount: 15,
        slogan: 'Perfect sink installation.',
        includes: [
          'Sink setup',
          'Pipe connection',
          'Testing',
        ],
        rating: 4.4,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Sink Replacement',
        price: 900,
        imagePath: 'assets/sink.jpg',
        description: 'Replace old sinks easily.',
        time: '40-60 mins',
        discount: 20,
        slogan: 'Upgrade your sink.',
        includes: [
          'Remove old sink',
          'Install new sink',
          'Testing',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],
  },

  /// 🧹 CLEANING SERVICES
  "Cleaning": {
    /// 🏠 HOME CLEANING
    "Home Cleaning": [
      ServiceProduct(
        name: "1 BHK Full Cleaning",
        price: 999,
        imagePath: "assets/cleaning.png",
        description: "Complete cleaning for small homes",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "2–3 Hours",
        discount: 20,
        finalPrice: 799,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "2 BHK Full Cleaning",
        price: 1499,
        imagePath: "assets/cleaning.png",
        description: "Perfect cleaning for medium homes",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "3–4 Hours",
        discount: 20,
        finalPrice: 1199,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "3 BHK Full Cleaning",
        price: 1999,
        imagePath: "assets/cleaning.png",
        description: "Deep cleaning for large homes",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "4–5 Hours",
        discount: 25,
        finalPrice: 1499,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "Living Room Cleaning",
        price: 399,
        imagePath: "assets/cleaning.png",
        description: "Fresh and dust free living space",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "60 minutes",
        discount: 10,
        finalPrice: 359,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🍳 KITCHEN CLEANING
    "Kitchen Cleaning": [
      ServiceProduct(
        name: "Basic Kitchen Cleaning",
        price: 499,
        imagePath: "assets/cleaning.png",
        description: "Quick kitchen refresh",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "60 minutes",
        discount: 10,
        finalPrice: 449,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "Deep Kitchen Cleaning",
        price: 1199,
        imagePath: "assets/cleaning.png",
        description: "Remove grease and tough stains",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "2–3 Hours",
        discount: 20,
        finalPrice: 959,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🚿 BATHROOM CLEANING
    "Bathroom Cleaning": [
      ServiceProduct(
        name: "Basic Bathroom Cleaning",
        price: 399,
        imagePath: "assets/cleaning.png",
        description: "Quick bathroom refresh",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "45 minutes",
        discount: 10,
        finalPrice: 359,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "Deep Bathroom Cleaning",
        price: 799,
        imagePath: "assets/cleaning.png",
        description: "Remove stains and bacteria",
        includes: [],
        excludes: [],
        steps: [],
        tools: "",
        time: "90 minutes",
        discount: 15,
        finalPrice: 679,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🛋 SOFA CLEANING
    "Sofa Cleaning": [
      ServiceProduct(
        name: "Fabric Sofa Cleaning",
        price: 599,
        imagePath: "assets/cleaning.png",
        description: "Deep cleaning using shampoo and vacuum extraction",
        includes: ["Dust removal", "Shampoo wash", "Drying"],
        excludes: ["Fabric repair"],
        steps: ["Vacuum", "Shampoo", "Dry"],
        tools: "Machine, shampoo solution",
        time: "60 Minutes",
        discount: 15,
        finalPrice: 509,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "Leather Sofa Cleaning",
        price: 699,
        imagePath: "assets/cleaning.png",
        description: "Safe cleaning for leather surfaces",
        includes: ["Cleaning and polishing"],
        excludes: ["Crack repair"],
        steps: ["Wipe", "Condition", "Polish"],
        tools: "Leather cleaner",
        time: "45 Minutes",
        discount: 15,
        finalPrice: 594,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🧹 CARPET CLEANING
    "Carpet Cleaning": [
      ServiceProduct(
        name: "Dry Carpet Cleaning",
        price: 399,
        imagePath: "assets/cleaning.png",
        description: "Quick dust removal cleaning",
        includes: ["Vacuum cleaning"],
        excludes: ["Wet wash"],
        steps: ["Vacuum", "Finish"],
        tools: "Vacuum",
        time: "30 Minutes",
        discount: 10,
        finalPrice: 359,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🪟 WINDOW CLEANING
    "Window Cleaning": [
      ServiceProduct(
        name: "Glass Cleaning",
        price: 299,
        imagePath: "assets/cleaning.png",
        description: "Streak-free glass cleaning",
        includes: ["Glass wipe"],
        excludes: ["High-rise work"],
        steps: ["Spray", "Wipe", "Polish"],
        tools: "Glass cleaner",
        time: "30 Minutes",
        discount: 10,
        finalPrice: 269,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🧽 DEEP CLEANING
    "Deep Cleaning": [
      ServiceProduct(
        name: "Full Home Deep Cleaning",
        price: 3999,
        imagePath: "assets/cleaning.png",
        description: "Complete deep cleaning of entire home",
        includes: ["All rooms deep cleaning"],
        excludes: ["Repair"],
        steps: ["Inspection", "Deep clean", "Finish"],
        tools: "Machines",
        time: "5–6 Hours",
        discount: 25,
        finalPrice: 2999,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🏢 CORPORATE CLEANING
    "Corporate Office Cleaning": [
      ServiceProduct(
        name: "Office Deep Cleaning",
        price: 4999,
        imagePath: "assets/cleaning.png",
        description: "Full office cleaning service",
        includes: ["All areas"],
        excludes: ["IT repair"],
        steps: ["Clean", "Sanitize"],
        tools: "Machines",
        time: "4–5 Hours",
        discount: 20,
        finalPrice: 3999,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔌 ELECTRONIC CLEANING
    "Electronic Cleaning": [
      ServiceProduct(
        name: "AC Cleaning",
        price: 599,
        imagePath: "assets/cleaning.png",
        description: "Improves AC performance",
        includes: ["Filter cleaning"],
        excludes: ["Gas refill"],
        steps: ["Open", "Clean", "Close"],
        tools: "AC kit",
        time: "60 Minutes",
        discount: 15,
        finalPrice: 509,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 📦 MONTHLY PACKAGES
    "Monthly Packages": [
      ServiceProduct(
        name: "Basic Plan",
        price: 1499,
        imagePath: "assets/cleaning.png",
        description: "Weekly cleaning plan",
        includes: ["4 visits/month"],
        excludes: ["Deep cleaning"],
        steps: [],
        tools: "",
        time: "60–90 min/visit",
        discount: 20,
        finalPrice: 1199,
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: "Premium Plan",
        price: 4999,
        imagePath: "assets/cleaning.png",
        description: "Deep + regular cleaning",
        includes: ["12 visits + deep cleaning"],
        excludes: ["Repair work"],
        steps: [],
        tools: "",
        time: "2–3 hrs/visit",
        discount: 30,
        finalPrice: 3499,
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],
  },
};
