import '../models/service_product.dart';

// Master data for all services and their subcategories
final Map<String, Map<String, List<ServiceProduct>>> serviceProducts = {
// 👕 LAUNDRY
  'Laundry': {
    /// WASHING
    'Washing': [
      ServiceProduct(
        name: 'Shirt Washing',
        price: 60,
        imagePath: 'assets/wash.jfif',
        description:
            'Professional cleaning to remove dirt, sweat, and stains while keeping fabric fresh and soft.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Fresh and clean shirt washing service.',
        includes: [
          'Deep fabric cleaning',
          'Quality detergent washing',
          'Fabric softener treatment',
          'Fresh fragrance finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Pant Washing',
        price: 70,
        imagePath: 'assets/pant.jpg',
        description:
            'Proper cleaning for trousers and everyday pants while maintaining fabric quality and color.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Proper washing for everyday pants.',
        includes: [
          'Deep fabric cleaning',
          'Color protection',
          'Fabric softener treatment',
          'Proper drying process',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Suit Washing',
        price: 200,
        imagePath: 'assets/blazzer.jpg',
        description:
            'Careful washing for formal suits with premium fabric care.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Careful washing for formal suits.',
        includes: [
          'Premium fabric care',
          'Deep stain removal',
          'Shape retention',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Saree Washing',
        price: 150,
        imagePath: 'assets/saree.jpg',
        description:
            'Gentle cleaning for delicate sarees while protecting fabric, color, and design.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Gentle washing for delicate sarees.',
        includes: [
          'Gentle washing process',
          'Fabric protection',
          'Color-safe cleaning',
          'Fresh fragrance finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Curtain Washing',
        price: 120,
        imagePath: 'assets/curtain.jpg',
        description:
            'Removes dust, stains, and allergens to keep curtains fresh and hygienic.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Dust-free and fresh curtain washing.',
        includes: [
          'Deep dust removal',
          'Fabric-safe washing',
          'Color protection',
          'Fresh fragrance',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Shoe Washing',
        price: 130,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning to remove dirt, stains, and odor while restoring freshness.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Clean and refreshed shoes.',
        includes: [
          'Dirt and stain removal',
          'Deep washing process',
          'Odor cleaning',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bedsheet Washing',
        price: 90,
        imagePath: 'assets/sheets.jpg',
        description:
            'Ensures hygienic cleaning and removal of dirt, bacteria, and stains.',
        time: '24 Hours',
        discount: 8,
        slogan: 'Soft, fresh and hygienic bedsheets.',
        includes: [
          'Hygienic deep cleaning',
          'Soft fabric care',
          'Fresh fragrance finish',
          'Proper drying and folding',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 DRY CLEANING
    'Dry Cleaning': [
      ServiceProduct(
        name: 'Shirt Dry Cleaning',
        price: 120,
        imagePath: 'assets/shirt.jpg',
        description: 'Professional dry cleaning for shirts with stain removal.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Professional dry cleaning for shirts.',
        includes: [
          'Deep stain removal',
          'Premium fabric care',
          'Safe chemical cleaning',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Suit Dry Cleaning',
        price: 350,
        imagePath: 'assets/blazzer.jpg',
        description: 'Premium cleaning service for formal suits.',
        time: '72 Hours',
        discount: 15,
        slogan: 'Premium cleaning for formal suits.',
        includes: [
          'Luxury fabric care',
          'Deep stain removal',
          'Shape retention',
          'Professional finishing',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Saree Dry Cleaning',
        price: 250,
        imagePath: 'assets/saree.jpg',
        description: 'Safe cleaning for delicate sarees with color protection.',
        time: '72 Hours',
        discount: 12,
        slogan: 'Safe dry cleaning for delicate sarees.',
        includes: [
          'Color protection',
          'Fabric-safe cleaning',
          'Soft finishing',
          'Premium care',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Blazer Dry Cleaning',
        price: 300,
        imagePath: 'assets/blazzer.jpg',
        description: 'Expert cleaning for blazers and jackets.',
        time: '72 Hours',
        discount: 10,
        slogan: 'Keep your blazer sharp and fresh.',
        includes: [
          'Odor removal',
          'Shape retention',
          'Soft fabric care',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 IRONING
    'Ironing': [
      ServiceProduct(
        name: 'Shirt Ironing',
        price: 15,
        imagePath: 'assets/ironing.jpg',
        description: 'Crisp and wrinkle-free shirt ironing.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Crisp and wrinkle-free shirts.',
        includes: [
          'Smooth finish',
          'Fabric-safe heat',
          'Neat folding',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Pant Ironing',
        price: 20,
        imagePath: 'assets/pant.jpg',
        description: 'Perfectly pressed pants.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Perfectly pressed pants.',
        includes: [
          'Sharp crease',
          'Wrinkle-free',
          'Professional finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Dress Ironing',
        price: 30,
        imagePath: 'assets/dress.jpg',
        description: 'Wrinkle-free dresses.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Wrinkle-free dresses every time.',
        includes: [
          'Soft pressing',
          'Neat finish',
          'Quick service',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Kids Clothes Ironing',
        price: 10,
        imagePath: 'assets/kids.jfif',
        description: 'Gentle ironing for kids’ clothes.',
        time: 'Same Day',
        discount: 5,
        slogan: 'Soft care for little ones.',
        includes: [
          'Delicate handling',
          'Smooth finish',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 CURTAIN CLEANING
    'Curtain Cleaning': [
      ServiceProduct(
        name: 'Window Curtain Cleaning',
        price: 120,
        imagePath: 'assets/curtain.jpg',
        description: 'Dust-free curtain cleaning.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Dust-free and fresh curtains.',
        includes: [
          'Deep dust removal',
          'Fabric-safe wash',
          'Fresh fragrance',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Heavy Curtain Cleaning',
        price: 200,
        imagePath: 'assets/curtain.jpg',
        description: 'Deep cleaning for heavy curtains.',
        time: '72 Hours',
        discount: 12,
        slogan: 'Deep cleaning for heavy curtains.',
        includes: [
          'Heavy fabric care',
          'Stain removal',
          'Odor removal',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Luxury Curtain Cleaning',
        price: 300,
        imagePath: 'assets/curtain.jpg',
        description: 'Premium cleaning for luxury curtains.',
        time: '72 Hours',
        discount: 15,
        slogan: 'Luxury care for your curtains.',
        includes: [
          'Color protection',
          'Premium fabric care',
          'Fresh scent',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 SHOE CLEANING
    'Shoe Cleaning': [
      ServiceProduct(
        name: 'Sports Shoe Cleaning',
        price: 150,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning for sports shoes with stain and odor removal.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Restore the freshness of sports shoes.',
        includes: [
          'Dirt and stain removal',
          'Odor cleaning',
          'Deep washing process',
          'Proper drying'
        ],
        process: [
          'Step 1: Inspection',
          'Step 2: Cleaning',
          'Step 3: Drying',
          'Step 4: Final check'
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Leather Shoe Cleaning',
        price: 200,
        imagePath: 'assets/leather.jpg',
        description:
            'Premium cleaning service for leather shoes with special care.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Premium care for leather shoes.',
        includes: [
          'Dirt removal',
          'Leather-safe cleaning',
          'Odor treatment',
          'Proper drying'
        ],
        rating: 4.3,
        process: [
          'Step 1: Inspection',
          'Step 2: Leather-safe cleaning',
          'Step 3: Conditioning',
          'Step 4: Drying'
        ],
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Sneaker Cleaning',
        price: 180,
        imagePath: 'assets/shoe.jpg',
        description:
            'Deep cleaning for sneakers to maintain style and hygiene.',
        time: '48 Hours',
        discount: 10,
        slogan: 'Deep cleaning for trendy sneakers.',
        includes: ['Stain removal', 'Odor cleaning', 'Deep wash', 'Drying'],
        process: [
          'Step 1: Inspection',
          'Step 2: Cleaning',
          'Step 3: Drying',
          'Step 4: Finishing'
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Boot Cleaning',
        price: 220,
        imagePath: 'assets/boots.jfif',
        description: 'Special cleaning for boots to maintain shine and shape.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Shiny and fresh boots every time.',
        includes: [
          'Deep dirt removal',
          'Polish treatment',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
    ],

    /// 🔹 BEDSHEET CLEANING
    'Bedsheet Cleaning': [
      ServiceProduct(
        name: 'Single Bedsheet Cleaning',
        price: 80,
        imagePath: 'assets/sheets.jpg',
        description: 'Hygienic bedsheet cleaning.',
        time: '24 Hours',
        discount: 8,
        slogan: 'Fresh and hygienic bedsheets.',
        includes: [
          'Hygienic wash',
          'Soft fabric care',
          'Proper drying',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Double Bedsheet Cleaning',
        price: 120,
        imagePath: 'assets/sheets.jpg',
        description: 'Soft and clean bedsheets.',
        time: '24 Hours',
        discount: 10,
        slogan: 'Soft and clean double bedsheets.',
        includes: [
          'Deep cleaning',
          'Soft finish',
          'Fresh fragrance',
        ],
        rating: 4.5,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Bedsheet Deep Cleaning',
        price: 180,
        imagePath: 'assets/sheets.jpg',
        description: 'Deep hygienic cleaning.',
        time: '48 Hours',
        discount: 12,
        slogan: 'Deep hygienic cleaning for bedsheets.',
        includes: [
          'Bacteria removal',
          'Deep stain cleaning',
          'Premium wash',
        ],
        rating: 4.3,
        id: '',
        service: '',
      ),
      ServiceProduct(
        name: 'Luxury Bedsheet Cleaning',
        price: 250,
        imagePath: 'assets/sheets.jpg',
        description: 'Premium care for luxury bedsheets.',
        time: '48 Hours',
        discount: 15,
        slogan: 'Luxury care for your bedsheets.',
        includes: [
          'Fabric-safe deep wash',
          'Premium finishing',
          'Fresh fragrance',
        ],
        rating: 5,
        id: '',
        service: '',
      ),
    ],
  },

// 🚰 PLUMBING
  'Plumbing': {
    /// 🔹 PIPE REPAIR
    'Pipe Repair': [
  ServiceProduct(
    name: 'Pipe Leakage Repair',
    price: 400,
    imagePath: 'assets/Plumber fixing leaking pipe .png',
    description: 'This service fixes leaking pipes to prevent water damage and wastage. Our professionals identify the source and repair it efficiently for long lasting results.',
    time: '45 mins',
    discount: 10,
    slogan: 'Quick fix for leaking pipes',
    includes: [
      'Inspection of leakage',
      'Leak detection',
      'Pipe repair work',
      'Sealing and testing',
    ],
    process: [
      'Inspection of pipe',
      'Leakage identification',
      'Repair and sealing',
      'Final testing',
    ],
    rating: 4.5,
    id: 'pipe_1',
    service: 'Pipe Repair',
  ),

  ServiceProduct(
    name: 'Broken Pipe Fix',
    price: 600,
    imagePath: 'assets/Broken pipe repair.png',
    description: 'Repair or replacement of damaged pipes to restore proper water flow and prevent further issues.',
    time: '60 mins',
    discount: 15,
    slogan: 'Reliable repair for damaged pipes',
    includes: [
      'Damage inspection',
      'Pipe fixing or replacement',
      'Leak testing',
    ],
    process: [
      'Damage inspection',
      'Pipe fixing or replacement',
      'Testing',
    ],
    rating: 4.4,
    id: 'pipe_2',
    service: 'Pipe Repair',
  ),

  ServiceProduct(
    name: 'Pipe Replacement',
    price: 1200,
    imagePath: 'assets/pipe replace.jfif',
    description: 'Complete pipe replacement service for long-lasting performance.',
    time: '90 mins',
    discount: 20,
    slogan: 'Complete replacement for long lasting use',
    includes: [
      'Old pipe removal',
      'New pipe installation',
      'Testing',
    ],
    process: [
      'Remove old pipe',
      'Install new pipe',
      'Testing',
    ],
    rating: 4.3,
    id: 'pipe_3',
    service: 'Pipe Repair',
  ),

  ServiceProduct(
    name: 'Pipe Joint Repair',
    price: 350,
    imagePath: 'assets/Joint Pipe Repair.jfif',
    description: 'Fix leaking pipe joints with precision to prevent water loss.',
    time: '40 mins',
    discount: 10,
    slogan: 'Fix leaking joints with precision',
    includes: [
      'Joint inspection',
      'Seal fixing',
      'Testing',
    ],
    process: [
      'Inspect joint',
      'Fix leakage',
      'Testing',
    ],
    rating: 4.3,
    id: 'pipe_4',
    service: 'Pipe Repair',
  ),

  ServiceProduct(
    name: 'Wall Pipe Repair',
    price: 700,
    imagePath: 'assets/Wall Pipe Repair.jfif',
    description: 'Safe repair of hidden wall pipes without damaging structure.',
    time: '60 mins',
    discount: 15,
    slogan: 'Safe repair of hidden wall pipes',
    includes: [
      'Wall inspection',
      'Pipe repair',
      'Leak testing',
    ],
    process: [
      'Inspect wall pipe',
      'Repair work',
      'Testing',
    ],
    rating: 4.4,
    id: 'pipe_5',
    service: 'Pipe Repair',
  ),
],

    /// 🔹 LEAKAGE FIX
   'Leakage Fix': [
  ServiceProduct(
    name: 'Kitchen Pipe Leakage Fix',
    price: 400,
    imagePath: 'assets/kitchen pipe fix.jfif',
    description: 'Stop kitchen leaks quickly and prevent water damage.',
    time: '45 mins',
    discount: 10,
    slogan: 'Stop kitchen leaks quickly',
    includes: [
      'Leak detection',
      'Seal fixing',
      'Testing',
    ],
    process: [
      'Detect leak',
      'Fix leakage',
      'Testing',
    ],
    rating: 4.5,
    id: 'leak_1',
    service: 'Leakage Fix',
  ),

  ServiceProduct(
    name: 'Bathroom Pipe Leakage Fix',
    price: 450,
    imagePath: 'assets/Bathroom Pipe Leakage Fix.jfif',
    description: 'Fix bathroom leaks efficiently and avoid further damage.',
    time: '45 mins',
    discount: 10,
    slogan: 'Fix bathroom leaks efficiently',
    includes: [
      'Inspection',
      'Leak fixing',
      'Testing',
    ],
    process: [
      'Inspection',
      'Fix leakage',
      'Testing',
    ],
    rating: 4.5,
    id: 'leak_2',
    service: 'Leakage Fix',
  ),

  ServiceProduct(
    name: 'Pipe Joint Leakage Fix',
    price: 350,
    imagePath: 'assets/pipe join.jpeg',
    description: 'Seal joint leaks properly and prevent future issues.',
    time: '40 mins',
    discount: 10,
    slogan: 'Seal joint leaks properly',
    includes: [
      'Joint inspection',
      'Seal fixing',
      'Testing',
    ],
    process: [
      'Inspect joint',
      'Fix leakage',
      'Testing',
    ],
    rating: 4.3,
    id: 'leak_3',
    service: 'Leakage Fix',
  ),

  ServiceProduct(
    name: 'Tank Pipe Leakage Fix',
    price: 600,
    imagePath: 'assets/tank leak.jpeg',
    description: 'Fix tank pipe leakage permanently with strong sealing.',
    time: '60 mins',
    discount: 15,
    slogan: 'Fix tank pipe leakage permanently',
    includes: [
      'Tank inspection',
      'Leak repair',
      'Testing',
    ],
    process: [
      'Inspect tank pipe',
      'Repair leakage',
      'Final testing',
    ],
    rating: 4.4,
    id: 'leak_4',
    service: 'Leakage Fix',
  ),
],
    /// 🔹 TAP INSTALLATION
    'Tap Installation': [
  ServiceProduct(
    name: 'New Tap Installation',
    price: 300,
    imagePath: 'assets/new tap.jfif',
    description: 'Professional installation of new taps ensuring proper fitting and smooth water flow without leakage.',
    time: '30 mins',
    discount: 10,
    slogan: 'Install new taps with precision',
    includes: [
      'Tap fitting',
      'Connection setup',
      'Leak testing',
    ],
    rating: 4.5,
    id: 'tap_1',
    service: 'Tap Installation',
  ),

  ServiceProduct(
    name: 'Tap Replacement',
    price: 350,
    imagePath: 'assets/replace old tap.jfif',
    description: 'Replace old taps easily with secure fitting and testing.',
    time: '30 mins',
    discount: 10,
    slogan: 'Replace old taps easily',
    includes: [
      'Remove old tap',
      'Install new tap',
      'Testing',
    ],
    rating: 4.5,
    id: 'tap_2',
    service: 'Tap Installation',
  ),

  ServiceProduct(
    name: 'Tap Leakage Fix',
    price: 200,
    imagePath: 'assets/tap leak.jpeg',
    description: 'Fix dripping taps instantly and prevent water wastage.',
    time: '20 mins',
    discount: 10,
    slogan: 'Fix dripping taps instantly',
    includes: [
      'Leak inspection',
      'Seal fixing',
      'Testing',
    ],
    rating: 4.4,
    id: 'tap_3',
    service: 'Tap Installation',
  ),

  ServiceProduct(
    name: 'Mixer Tap Installation',
    price: 500,
    imagePath: 'assets/mix tap.jpg',
    description: 'Install modern mixer taps with hot and cold water setup.',
    time: '40 mins',
    discount: 15,
    slogan: 'Install modern mixer taps',
    includes: [
      'Mixer tap fitting',
      'Hot & cold connection',
      'Testing',
    ],
    rating: 4.6,
    id: 'tap_4',
    service: 'Tap Installation',
  ),

  ServiceProduct(
    name: 'Kitchen Tap Installation',
    price: 350,
    imagePath: 'assets/kitchen tap.jpg',
    description: 'Perfect kitchen tap setup with proper alignment and flow.',
    time: '30 mins',
    discount: 10,
    slogan: 'Perfect kitchen tap setup',
    includes: [
      'Tap installation',
      'Connection setup',
      'Flow testing',
    ],
    rating: 4.5,
    id: 'tap_5',
    service: 'Tap Installation',
  ),
],
    

    /// 🔹 DRAIN CLEANING
  'Drain Cleaning': [
  ServiceProduct(
    name: 'Kitchen Drain Cleaning',
    price: 400,
    imagePath: 'assets/kitchen drain.jpg',
    description: 'Cleaning of blocked kitchen drains to ensure smooth water flow and prevent bad odor.',
    time: '45 mins',
    discount: 10,
    slogan: 'Remove kitchen blockages quickly',
    includes: [
      'Blockage removal',
      'Drain cleaning',
      'Flow testing',
    ],
    rating: 4.5,
    id: 'drain_1',
    service: 'Drain Cleaning',
  ),

  ServiceProduct(
    name: 'Bathroom Drain Cleaning',
    price: 400,
    imagePath: 'assets/bath drain.jpeg',
    description: 'Keep bathroom drains clean and prevent clogging issues.',
    time: '45 mins',
    discount: 10,
    slogan: 'Keep bathroom drains clean',
    includes: [
      'Drain cleaning',
      'Block removal',
      'Testing',
    ],
    rating: 4.4,
    id: 'drain_2',
    service: 'Drain Cleaning',
  ),

  ServiceProduct(
    name: 'Blocked Drain Fix',
    price: 600,
    imagePath: 'assets/bloc drain.jpeg',
    description: 'Clear heavily blocked drains with advanced cleaning.',
    time: '60 mins',
    discount: 15,
    slogan: 'Clear heavily blocked drains',
    includes: [
      'Inspection',
      'Deep cleaning',
      'Testing',
    ],
    rating: 4.5,
    id: 'drain_3',
    service: 'Drain Cleaning',
  ),

  ServiceProduct(
    name: 'Drain Pipe Cleaning',
    price: 500,
    imagePath: 'assets/drain pipe.jpg',
    description: 'Deep cleaning for drain pipes to maintain smooth flow.',
    time: '50 mins',
    discount: 10,
    slogan: 'Deep cleaning for drain pipes',
    includes: [
      'Pipe inspection',
      'Cleaning process',
      'Final check',
    ],
    rating: 4.3,
    id: 'drain_4',
    service: 'Drain Cleaning',
  ),
],

    ///BATHROOM REPAIR
'Bathroom Repair': [
  ServiceProduct(
    name: 'Shower Repair',
    price: 400,
    imagePath: 'assets/shower repair.jfif',
    description: 'Fix faulty showers quickly with proper inspection and repair.',
    time: '40 mins',
    discount: 10,
    slogan: 'Fix faulty showers quickly',
    includes: [
      'Inspection',
      'Repair work',
      'Testing',
    ],
    rating: 4.5,
    id: 'bath_1',
    service: 'Bathroom Repair',
  ),

  ServiceProduct(
    name: 'Bathroom Pipe Repair',
    price: 600,
    imagePath: 'assets/bath pipe.png',
    description: 'Repair bathroom pipes efficiently and prevent leakages.',
    time: '60 mins',
    discount: 15,
    slogan: 'Repair bathroom pipes efficiently',
    includes: [
      'Pipe repair',
      'Leak fixing',
      'Testing',
    ],
    rating: 4.3,
    id: 'bath_2',
    service: 'Bathroom Repair',
  ),

  ServiceProduct(
    name: 'Shower Installation',
    price: 500,
    imagePath: 'assets/shower installation.jpg',
    description: 'Install new showers professionally with proper fittings.',
    time: '45 mins',
    discount: 10,
    slogan: 'Install new showers professionally',
    includes: [
      'Shower fitting',
      'Connection setup',
      'Testing',
    ],
    rating: 4.4,
    id: 'bath_3',
    service: 'Bathroom Repair',
  ),

  ServiceProduct(
    name: 'Wash Basin Pipe Repair',
    price: 400,
    imagePath: 'assets/basin repair.jfif',
    description: 'Fix wash basin pipe issues and ensure smooth flow.',
    time: '40 mins',
    discount: 10,
    slogan: 'Fix wash basin pipe issues',
    includes: [
      'Pipe inspection',
      'Repair',
      'Flow testing',
    ],
    rating: 4.2,
    id: 'bath_4',
    service: 'Bathroom Repair',
  ),
],


/// TOILET REPAIR 
      'Toilet Repair': [
  ServiceProduct(
    name: 'Toilet Flush Repair',
    price: 300,
    imagePath: 'assets/flush repair.jfif',
    description: 'Fixing issues with toilet flush system to ensure proper functionality and water control.',
    time: '30 mins',
    discount: 10,
    slogan: 'Fix flush issues quickly',
    includes: [
      'Flush inspection',
      'Repair work',
      'Testing',
    ],
    rating: 4.4,
    id: 'toilet_1',
    service: 'Toilet Repair',
  ),

  ServiceProduct(
    name: 'Toilet Leakage Fix',
    price: 450,
    imagePath: 'assets/toilet leakage.jpg',
    description: 'Stop toilet leaks effectively and prevent water wastage.',
    time: '45 mins',
    discount: 10,
    slogan: 'Stop toilet leaks effectively',
    includes: [
      'Leak detection',
      'Seal fixing',
      'Testing',
    ],
    rating: 4.5,
    id: 'toilet_2',
    service: 'Toilet Repair',
  ),

  ServiceProduct(
    name: 'Toilet Seat Replacement',
    price: 350,
    imagePath: 'assets/toilet seat.jfif',
    description: 'Replace damaged or old toilet seats with new ones.',
    time: '30 mins',
    discount: 10,
    slogan: 'Replace damaged toilet seats',
    includes: [
      'Seat removal',
      'New seat fitting',
      'Final check',
    ],
    rating: 4.3,
    id: 'toilet_3',
    service: 'Toilet Repair',
  ),

  ServiceProduct(
    name: 'Toilet Pipe Repair',
    price: 500,
    imagePath: 'assets/toilet pipe.jfif',
    description: 'Repair toilet pipe connections and fix leakages.',
    time: '45 mins',
    discount: 10,
    slogan: 'Repair toilet pipe connections',
    includes: [
      'Pipe inspection',
      'Repair',
      'Testing',
    ],
    rating: 4.2,
    id: 'toilet_4',
    service: 'Toilet Repair',
  ),

  ServiceProduct(
    name: 'Flush Tank Repair',
    price: 400,
    imagePath: 'assets/flush tank.jpg',
    description: 'Fix flush tank problems and ensure proper water flow.',
    time: '40 mins',
    discount: 10,
    slogan: 'Fix flush tank problems',
    includes: [
      'Tank inspection',
      'Repair',
      'Testing',
    ],
    rating: 4.3,
    id: 'toilet_5',
    service: 'Toilet Repair',
  ),
],

    /// 🔹 SINK INSTALLATION
'Sink Installation': [
  ServiceProduct(
    name: 'Kitchen Sink Installation',
    price: 800,
    imagePath: 'assets/kitchen sink.jpg',
    description: 'Installation of kitchen sink with proper pipe connection and leakage prevention.',
    time: '60 mins',
    discount: 15,
    slogan: 'Install kitchen sinks perfectly',
    includes: [
      'Sink fitting',
      'Pipe connection',
      'Leak testing',
    ],
    rating: 4.4,
    id: 'sink_1',
    service: 'Sink Installation',
  ),

  ServiceProduct(
    name: 'Wash Basin Installation',
    price: 700,
    imagePath: 'assets/wash basin.jfif',
    description: 'Professional wash basin installation with proper fittings.',
    time: '60 mins',
    discount: 15,
    slogan: 'Professional basin installation',
    includes: [
      'Basin fitting',
      'Pipe connection',
      'Leak testing',
    ],
    rating: 4.3,
    id: 'sink_2',
    service: 'Sink Installation',
  ),

  ServiceProduct(
    name: 'Sink Replacement',
    price: 900,
    imagePath: 'assets/sink replace.jfif',
    description: 'Replace old sinks easily with new installation and testing.',
    time: '60 mins',
    discount: 20,
    slogan: 'Replace old sinks easily',
    includes: [
      'Remove old sink',
      'Install new sink',
      'Testing',
    ],
    rating: 4.5,
    id: 'sink_3',
    service: 'Sink Installation',
  ),

  ServiceProduct(
    name: 'Sink Pipe Connection',
    price: 400,
    imagePath: 'assets/sink pipe.jpg',
    description: 'Ensure proper sink pipe connection for smooth water flow.',
    time: '40 mins',
    discount: 10,
    slogan: 'Proper sink pipe connections',
    includes: [
      'Pipe fitting',
      'Connection setup',
      'Flow testing',
    ],
    rating: 4.2,
    id: 'sink_4',
    service: 'Sink Installation',
  ),

  ServiceProduct(
    name: 'Sink Leakage Repair',
    price: 400,
    imagePath: 'assets/sink leakage.png',
    description: 'Fix sink leakage issues quickly and effectively.',
    time: '40 mins',
    discount: 10,
    slogan: 'Fix sink leakage issues quickly',
    includes: [
      'Leak detection',
      'Seal fixing',
      'Final testing',
    ],
    rating: 4.3,
    id: 'sink_5',
    service: 'Sink Installation',
  ),
],

/// WATER TANK INSTALLATION 

'Water Tank Installation': [
  ServiceProduct(
    name: 'Basic Tank Installation',
    price: 999,
    imagePath: 'assets/basic tank.jfif',
    description: 'Basic water tank installation with proper placement and pipe connection.',
    time: '60 mins',
    discount: 10,
    slogan: 'Quick setup, smooth flow',
    includes: [
      'Tank placement',
      'Pipe connection',
      'Inlet & outlet setup',
      'Leak testing',
    ],
    process: [
      'Tank positioning',
      'Pipe connection',
      'Fitting setup',
      'Final testing',
    ],
    rating: 4.4,
    id: 'wt_1',
    service: 'Water Tank Installation',
  ),

  ServiceProduct(
    name: 'Standard Tank Installation',
    price: 1799,
    imagePath: 'assets/standard tank.jfif',
    description: 'Standard installation with complete pipe alignment and overflow setup.',
    time: '120 mins',
    discount: 12,
    slogan: 'Reliable installation, long-lasting performance',
    includes: [
      'Tank installation',
      'Pipe alignment',
      'Float valve setup',
      'Overflow connection',
      'Leak testing',
    ],
    process: [
      'Install tank',
      'Align pipes',
      'Valve setup',
      'Testing',
    ],
    rating: 4.5,
    id: 'wt_2',
    service: 'Water Tank Installation',
  ),

  ServiceProduct(
    name: 'Premium Tank Installation',
    price: 2999,
    imagePath: 'assets/premium tank.jfif',
    description: 'Complete installation with motor connection and advanced sealing.',
    time: '180 mins',
    discount: 15,
    slogan: 'Strong installation, worry-free water',
    includes: [
      'Full tank installation',
      'Motor connection',
      'Heavy-duty fittings',
      'Auto cut-off setup',
      'Anti-leak sealing',
      'Testing',
    ],
    process: [
      'Install tank',
      'Connect motor',
      'Setup auto system',
      'Final testing',
    ],
    rating: 4.6,
    id: 'wt_3',
    service: 'Water Tank Installation',
  ),

  ServiceProduct(
    name: 'Advanced Tank Installation',
    price: 4999,
    imagePath: 'assets/adavnced tank.jfif',
    description: 'Advanced installation with smart automation and pressure balancing.',
    time: '240 mins',
    discount: 18,
    slogan: 'Smart water system for modern homes',
    includes: [
      'Premium tank setup',
      'Smart sensor/float setup',
      'Motor automation',
      'Pressure balancing',
      'Safety checks',
      'Final inspection',
    ],
    process: [
      'Install tank',
      'Setup smart system',
      'Balance pressure',
      'Final inspection',
    ],
    rating: 4.7,
    id: 'wt_4',
    service: 'Water Tank Installation',
  ),
],
  },
};