// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTpLsJUD030-V6VYY8HY5kQH4AV3S1OM',
    appId: '1:240198181802:web:2d6ced041350d97148c1d3',
    messagingSenderId: '240198181802',
    projectId: 'callme-2f7fe',
    authDomain: 'callme-2f7fe.firebaseapp.com',
    storageBucket: 'callme-2f7fe.firebasestorage.app',
    measurementId: 'G-ECJLHZHPG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZgkNCOXpLHk7Xbc42eoxX4UCdpD7BVE',
    appId: '1:240198181802:android:a158222d3d63727048c1d3',
    messagingSenderId: '240198181802',
    projectId: 'callme-2f7fe',
    storageBucket: 'callme-2f7fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhdznanHNXBbKSFHdbL-zRsA_e0LPcjE',
    appId: '1:240198181802:ios:b835448da1b2ed6948c1d3',
    messagingSenderId: '240198181802',
    projectId: 'callme-2f7fe',
    storageBucket: 'callme-2f7fe.firebasestorage.app',
    iosBundleId: 'com.example.callme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnhdznanHNXBbKSFHdbL-zRsA_e0LPcjE',
    appId: '1:240198181802:ios:b835448da1b2ed6948c1d3',
    messagingSenderId: '240198181802',
    projectId: 'callme-2f7fe',
    storageBucket: 'callme-2f7fe.firebasestorage.app',
    iosBundleId: 'com.example.callme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTpLsJUD030-V6VYY8HY5kQH4AV3S1OM',
    appId: '1:240198181802:web:8e4b0e7ba54cbdac48c1d3',
    messagingSenderId: '240198181802',
    projectId: 'callme-2f7fe',
    authDomain: 'callme-2f7fe.firebaseapp.com',
    storageBucket: 'callme-2f7fe.firebasestorage.app',
    measurementId: 'G-0R6DEDE3K7',
  );
}
