import '../models/service_product.dart';

final Map<String, List<ServiceProduct>> waterServices = {
  /// 🔷 COMMERCIAL WATER SERVICES
  "Commercial Water Services": [
    ServiceProduct(
      id: "cws1",
      service: "Water Services",
      name: "Used Water Removal",
      price: 1500,
      imagePath: "assets/water.png",
      description: "Safe removal of wastewater from commercial areas",
      discount: 8,
      finalPrice: 1380,
      time: "Per Visit",
    ),
    ServiceProduct(
      id: "cws2",
      service: "Water Services",
      name: "Industrial Water Disposal",
      price: 3000,
      imagePath: "assets/water.png",
      description: "Bulk disposal service for factories and industries",
      discount: 10,
      finalPrice: 2700,
    ),
    ServiceProduct(
      id: "cws3",
      service: "Water Services",
      name: "Construction Site Water Supply",
      price: 2000,
      imagePath: "assets/water.png",
      description: "Water supply for construction work",
      discount: 12,
      finalPrice: 1760,
    ),
    ServiceProduct(
      id: "cws4",
      service: "Water Services",
      name: "Farming Water Supply",
      price: 1800,
      imagePath: "assets/water.png",
      description: "Water supply for irrigation and farming",
      discount: 10,
      finalPrice: 1620,
    ),
    ServiceProduct(
      id: "cws5",
      service: "Water Services",
      name: "Septic Tank Cleaning",
      price: 2500,
      imagePath: "assets/water.png",
      description: "Cleaning and maintenance of septic tanks",
      discount: 10,
      finalPrice: 2250,
    ),
    ServiceProduct(
      id: "cws6",
      service: "Water Services",
      name: "Drainage Cleaning",
      price: 1000,
      imagePath: "assets/water.png",
      description: "Clearing blocked drainage systems",
      discount: 8,
      finalPrice: 920,
    ),
  ],

  /// 🔷 AQUA INSTALLATION
  "Aqua Installation": [
    ServiceProduct(
      id: "ai1",
      service: "Water Services",
      name: "RO Installation",
      price: 800,
      imagePath: "assets/water.png",
      description: "Installation of water purifier systems",
      discount: 10,
      finalPrice: 720,
    ),
    ServiceProduct(
      id: "ai2",
      service: "Water Services",
      name: "RO Service & Repair",
      price: 500,
      imagePath: "assets/water.png",
      description: "Maintenance and repair of RO systems",
      discount: 8,
      finalPrice: 460,
    ),
    ServiceProduct(
      id: "ai3",
      service: "Water Services",
      name: "Commercial RO Setup",
      price: 15000,
      imagePath: "assets/water.png",
      description: "Large-scale purification system setup",
      discount: 12,
      finalPrice: 13200,
    ),
    ServiceProduct(
      id: "ai4",
      service: "Water Services",
      name: "Filter Replacement",
      price: 300,
      imagePath: "assets/water.png",
      description: "Changing filters for better water quality",
      discount: 5,
      finalPrice: 285,
    ),
  ],

  /// 🔷 ICE SUPPLY
  "Ice Supply": [
    ServiceProduct(
      id: "ice1",
      service: "Water Services",
      name: "Ice Blocks",
      price: 150,
      imagePath: "assets/water.png",
      description: "Large ice blocks for storage",
      discount: 5,
      finalPrice: 142,
    ),
    ServiceProduct(
      id: "ice2",
      service: "Water Services",
      name: "Ice Cubes (10kg)",
      price: 250,
      imagePath: "assets/water.png",
      description: "Clean cubes for drinks",
      discount: 8,
      finalPrice: 230,
    ),
    ServiceProduct(
      id: "ice3",
      service: "Water Services",
      name: "Crushed Ice",
      price: 200,
      imagePath: "assets/water.png",
      description: "Perfect for beverages",
      discount: 8,
      finalPrice: 184,
    ),
    ServiceProduct(
      id: "ice4",
      service: "Water Services",
      name: "Party Ice Supply",
      price: 1000,
      imagePath: "assets/water.png",
      description: "Bulk ice supply for events",
      discount: 10,
      finalPrice: 900,
    ),
  ],

  /// 🔷 TANKER SUPPLY
  "Tanker Supply": [
    ServiceProduct(
      id: "tank1",
      service: "Water Services",
      name: "3000L Mini Tanker",
      price: 800,
      imagePath: "assets/water.png",
      description: "Water supply for small homes",
      discount: 8,
      finalPrice: 736,
    ),
    ServiceProduct(
      id: "tank2",
      service: "Water Services",
      name: "5000L Residential Tanker",
      price: 1200,
      imagePath: "assets/water.png",
      description: "Regular household supply",
      discount: 10,
      finalPrice: 1080,
    ),
    ServiceProduct(
      id: "tank3",
      service: "Water Services",
      name: "10000L Commercial Tanker",
      price: 2200,
      imagePath: "assets/water.png",
      description: "Bulk supply for industries",
      discount: 12,
      finalPrice: 1936,
    ),
    ServiceProduct(
      id: "tank4",
      service: "Water Services",
      name: "Emergency Tanker",
      price: 1500,
      imagePath: "assets/water.png",
      description: "Quick supply during shortage",
      discount: 5,
      finalPrice: 1425,
    ),
  ],

  /// 🔷 WATER BOTTLES
  "Water Bottles": [
    ServiceProduct(
      id: "wb1",
      service: "Water Services",
      name: "1L Bottles (Pack of 12)",
      price: 180,
      imagePath: "assets/water.png",
      description: "Standard bottled water",
      discount: 5,
      finalPrice: 171,
    ),
    ServiceProduct(
      id: "wb2",
      service: "Water Services",
      name: "500ml Bottles (Pack of 24)",
      price: 200,
      imagePath: "assets/water.png",
      description: "Compact bottles",
      discount: 5,
      finalPrice: 190,
    ),
    ServiceProduct(
      id: "wb3",
      service: "Water Services",
      name: "250ml Bottles (Pack of 48)",
      price: 300,
      imagePath: "assets/water.png",
      description: "Small bottles for events",
      discount: 8,
      finalPrice: 276,
    ),
    ServiceProduct(
      id: "wb4",
      service: "Water Services",
      name: "Custom Label Bottles",
      price: 15,
      imagePath: "assets/water.png",
      description: "Personalized bottles",
      discount: 10,
      finalPrice: 13,
    ),
  ],

  /// 🔷 JAR EXCHANGE
  "Jar Exchange / Return": [
    ServiceProduct(
      id: "jar1",
      service: "Water Services",
      name: "20L Jar Exchange",
      price: 40,
      imagePath: "assets/water.png",
      description: "Exchange empty jars with fresh ones",
      discount: 5,
      finalPrice: 38,
    ),
    ServiceProduct(
      id: "jar2",
      service: "Water Services",
      name: "Empty Jar Pickup",
      price: 20,
      imagePath: "assets/water.png",
      description: "Doorstep pickup service",
      discount: 0,
      finalPrice: 20,
    ),
    ServiceProduct(
      id: "jar3",
      service: "Water Services",
      name: "Monthly Subscription",
      price: 1100,
      imagePath: "assets/water.png",
      description: "Monthly delivery service",
      discount: 10,
      finalPrice: 990,
    ),
    ServiceProduct(
      id: "jar4",
      service: "Water Services",
      name: "Urgent Jar Delivery",
      price: 60,
      imagePath: "assets/water.png",
      description: "Same-day delivery",
      discount: 5,
      finalPrice: 57,
    ),
  ],

  /// 🔷 BRAND WATER
  "Brand Water": [
    ServiceProduct(
      id: "bw1",
      service: "Water Services",
      name: "20L Drinking Water Jar",
      price: 60,
      imagePath: "assets/water.png",
      description: "BIS-certified drinking water",
      discount: 5,
      finalPrice: 57,
    ),
    ServiceProduct(
      id: "bw2",
      service: "Water Services",
      name: "Premium Mineral Water",
      price: 90,
      imagePath: "assets/water.png",
      description: "Mineral-rich water",
      discount: 8,
      finalPrice: 83,
    ),
    ServiceProduct(
      id: "bw3",
      service: "Water Services",
      name: "Alkaline Water",
      price: 120,
      imagePath: "assets/water.png",
      description: "Healthy alkaline water",
      discount: 10,
      finalPrice: 108,
    ),
    ServiceProduct(
      id: "bw4",
      service: "Water Services",
      name: "Himalayan Natural Water",
      price: 150,
      imagePath: "assets/water.png",
      description: "Natural mineral water",
      discount: 12,
      finalPrice: 132,
    ),
    ServiceProduct(
      id: "bw5",
      service: "Water Services",
      name: "Ganga Jal",
      price: 50,
      imagePath: "assets/water.png",
      description: "Sacred water for pooja",
      discount: 0,
      finalPrice: 50,
    ),
    ServiceProduct(
      id: "bw6",
      service: "Water Services",
      name: "Temple Water Pack",
      price: 100,
      imagePath: "assets/water.png",
      description: "Water for rituals",
      discount: 5,
      finalPrice: 95,
    ),
    ServiceProduct(
      id: "bw7",
      service: "Water Services",
      name: "Distilled Water",
      price: 80,
      imagePath: "assets/water.png",
      description: "Medical/lab use water",
      discount: 8,
      finalPrice: 74,
    ),
  ],
};
